import XCTest
import AVFoundation
import CoreMedia
@testable import vcompress

/// Integration tests that use real AVFoundation and real filesystem.
/// These tests require the fixture video files generated by ffmpeg
/// in Tests/vcompressTests/Integration/Fixtures/.
///
/// Generate fixtures with:
///   ffmpeg -f lavfi -i testsrc2=duration=2:size=320x240:rate=30 \
///          -f lavfi -i sine=frequency=440:duration=2 \
///          -c:v libx264 -preset ultrafast -c:a aac \
///          Tests/vcompressTests/Integration/Fixtures/sample_h264.mov
///   ffmpeg -f lavfi -i testsrc2=duration=2:size=320x240:rate=30 \
///          -c:v libx265 -preset ultrafast \
///          Tests/vcompressTests/Integration/Fixtures/sample_hevc.mp4
///   ffmpeg -f lavfi -i sine=frequency=440:duration=2 \
///          -c:a aac \
///          Tests/vcompressTests/Integration/Fixtures/audio_only.mov
final class EncodeIntegrationTests: XCTestCase {

    private var tempDir: URL!

    override func setUp() async throws {
        try await super.setUp()
        tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("vcompress-integration-\(UUID().uuidString)")
        try FileManager.default.createDirectory(
            at: tempDir,
            withIntermediateDirectories: true
        )
    }

    override func tearDown() async throws {
        if let tempDir = tempDir {
            try? FileManager.default.removeItem(at: tempDir)
        }
        try await super.tearDown()
    }

    // MARK: - Fixture Helpers

    private func fixtureURL(_ name: String) -> URL {
        // Find the Fixtures directory relative to this test file
        let thisFile = URL(fileURLWithPath: #filePath)
        let fixturesDir = thisFile
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures")
        return fixturesDir.appendingPathComponent(name)
    }

    private func fixtureExists(_ name: String) -> Bool {
        FileManager.default.fileExists(atPath: fixtureURL(name).path)
    }

    // MARK: - Codec Detection Tests

    func test_realCodecDetection_h264() async throws {
        let fixture = fixtureURL("sample_h264.mov")
        guard fixtureExists("sample_h264.mov") else {
            throw XCTSkip("Fixture sample_h264.mov not found. Generate with ffmpeg.")
        }

        let inspector = RealAssetInspector()
        let codecs = try await inspector.videoTrackCodecs(forFileAt: fixture)
        XCTAssertEqual(codecs, [kCMVideoCodecType_H264])
    }

    func test_realCodecDetection_hevc() async throws {
        let fixture = fixtureURL("sample_hevc.mp4")
        guard fixtureExists("sample_hevc.mp4") else {
            throw XCTSkip("Fixture sample_hevc.mp4 not found. Generate with ffmpeg.")
        }

        let inspector = RealAssetInspector()
        let codecs = try await inspector.videoTrackCodecs(forFileAt: fixture)
        // ffmpeg libx265 may produce hev1 (0x68657631) instead of hvc1 (kCMVideoCodecType_HEVC)
        let hevcCodecs: Set<FourCharCode> = [kCMVideoCodecType_HEVC, FourCharCode(0x68657631)]
        XCTAssertEqual(codecs.count, 1)
        XCTAssertTrue(hevcCodecs.contains(codecs[0]), "Expected HEVC codec, got: \(codecs[0])")
    }

    func test_realCodecDetection_audioOnly_returnsEmpty() async throws {
        let fixture = fixtureURL("audio_only.mov")
        guard fixtureExists("audio_only.mov") else {
            throw XCTSkip("Fixture audio_only.mov not found. Generate with ffmpeg.")
        }

        let inspector = RealAssetInspector()
        let codecs = try await inspector.videoTrackCodecs(forFileAt: fixture)
        XCTAssertTrue(codecs.isEmpty, "Audio-only file should have no video codecs, got: \(codecs)")
    }

    // MARK: - Encode Integration Test

    func test_realEncode_h264ToHEVC() async throws {
        let source = fixtureURL("sample_h264.mov")
        guard fixtureExists("sample_h264.mov") else {
            throw XCTSkip("Fixture sample_h264.mov not found. Generate with ffmpeg.")
        }

        let dest = tempDir.appendingPathComponent("output.mov")
        let fs = RealFileSystem()
        let inspector = RealAssetInspector()
        let factory = RealExportSessionFactory()
        let encoder = Encoder(factory: factory, fs: fs, inspector: inspector)

        // Get source file size
        let sourceAttrs = try FileManager.default.attributesOfItem(atPath: source.path)
        let sourceSize = (sourceAttrs[.size] as? Int64)
            ?? (sourceAttrs[.size] as? NSNumber)?.int64Value
            ?? 0

        let entry = FileEntry(
            sourcePath: source.path,
            relativePath: "sample_h264.mov",
            destPath: dest.path,
            fileSize: sourceSize,
            sourceContainer: "mov"
        )

        try await encoder.encode(entry, quality: .standard)

        // Verify output exists
        XCTAssertTrue(FileManager.default.fileExists(atPath: dest.path), "Output file should exist")

        // Verify output is HEVC
        let codecs = try await inspector.videoTrackCodecs(forFileAt: dest)
        XCTAssertFalse(codecs.isEmpty, "Output should have video tracks")
        XCTAssertEqual(codecs.first, kCMVideoCodecType_HEVC, "Output should be HEVC")

        // Verify output is playable
        let playable = try await inspector.isPlayable(at: dest)
        XCTAssertTrue(playable, "Output should be playable")

        // Verify output has audio track
        let asset = AVURLAsset(url: dest)
        let audioTracks = try await asset.loadTracks(withMediaType: .audio)
        XCTAssertFalse(audioTracks.isEmpty, "Output should have audio track")
    }
}
